export const ON_CHANGE_VALUE = 'ON_CHANGE_VALUE';
export const LOG_OUT = 'LOG_OUT';
export const SET_LOADING_START = 'SET_LOADING_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const ADD_DANHGIA_START = 'ADD_DANHGIA_START'
export const ADD_DANHGIA_SUCCESS = 'ADD_DANHGIA_SUCCESS'
export const ADD_DANHGIA_FAIL = 'ADD_DANHGIA_FAIL'

export const SET_CAN_DANHGIA = 'SET_CAN_DANHGIA'
export const RESET_DANHGIA = 'RESET_DANHGIA'